// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Test.Models;

[Table("Department")]
[Index("DepartmentCode", Name = "UQ__Departme__6EA8896D244F2451", IsUnique = true)]
public partial class Department
{
    [Key]
    public int DepartmentID { get; set; }

    [Required]
    [StringLength(100)]
    public string DepartmentName { get; set; }

    [Required]
    [StringLength(10)]
    public string DepartmentCode { get; set; }

    [StringLength(100)]
    public string Location { get; set; }

    [StringLength(100)]
    public string HeadOfDepartment { get; set; }

    [InverseProperty("Department")]
    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}