// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Test.Models;

[Table("Student")]
[Index("Email", Name = "UQ__Students__A9D1053456FEB963", IsUnique = true)]
public partial class Student
{
    [Key]
    public int StudentID { get; set; }

    [Required]
    [StringLength(50)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(50)]
    public string LastName { get; set; }

    [StringLength(100)]
    public string Email { get; set; }

    [StringLength(20)]
    public string Phone { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public DateOnly? EnrollmentDate { get; set; }

    public int? DepartmentID { get; set; }

    [ForeignKey("DepartmentID")]
    [InverseProperty("Students")]
    //[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public virtual Department Department { get; set; }
}